# Generated by Django 4.1 on 2024-03-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_email", models.CharField(max_length=128)),
                ("sender_name", models.CharField(max_length=128)),
                ("content", models.TextField(max_length=5000)),
                ("is_read", models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
